"""Initial migration

Revision ID: 3d399f7d1103
Revises: 
Create Date: 2025-12-03 21:18:31.314554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d399f7d1103'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()

    # Check existence to avoid conflicts with tables created by .NET backend
    if 'users' not in tables and 'Users' not in tables:
        op.create_table('users',
        sa.Column('username', sa.String(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('password_hash', sa.String(), nullable=False),
        sa.Column('role', sa.Enum('ADMIN', 'USER', name='userrole'), nullable=False),
        sa.Column('refresh_token', sa.String(), nullable=True),
        sa.Column('refresh_token_expiry_time', sa.DateTime(), nullable=True),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('creation_date', sa.DateTime(), nullable=False),
        sa.Column('modification_date', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
    
    if 'documents' not in tables and 'Documents' not in tables:
        op.create_table('documents',
        sa.Column('file_name', sa.String(), nullable=False),
        sa.Column('storage_path', sa.String(), nullable=False),
        sa.Column('content_type', sa.String(), nullable=False),
        sa.Column('file_size', sa.BigInteger(), nullable=False),
        sa.Column('is_processed', sa.Boolean(), nullable=False),
        sa.Column('analysis_result', sa.String(), nullable=True),
        sa.Column('uploaded_by_user_id', sa.Integer(), nullable=False),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('creation_date', sa.DateTime(), nullable=False),
        sa.Column('modification_date', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    
    if 'event_logs' not in tables and 'EventLogs' not in tables:
        op.create_table('event_logs',
        sa.Column('event_type', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('creation_date', sa.DateTime(), nullable=False),
        sa.Column('modification_date', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_logs')
    op.drop_table('documents')
    op.drop_table('users')
    # ### end Alembic commands ###
